### ISSUE TITLE
Error starting bot

### ISSUE THREAD

**Issue by Auroric** [xKynn/PokeCatcher#2]
```libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "launch.py", line 8, in <module>
    opt_start(bot_type, int(ind))
  File "launcher.py", line 33, in launcher.opt_start
TypeError: 'int' object is not subscriptable
Traceback (most recent call last):
  File "launch.py", line 8, in <module>
    opt_start(bot_type, int(ind))
  File "launcher.py", line 30, in launcher.opt_start
TypeError: 'int' object is not subscriptable
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 224, in _run_event
    yield from coro(*args, **kwargs)
TypeError: 'coroutine' object is not iterable
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 224, in _run_event
    yield from coro(*args, **kwargs)
TypeError: 'coroutine' object is not iterable
```

**Comment by Hyperclaw79** [comment]
Hmm looks like a coro was forgotten to be awaited.
@xKynn Are you still working on this?

**Comment by xKynn** [comment]
Nah
