### ISSUE TITLE
Unregistered userID

### ISSUE THREAD

**Issue by madiajijah11** [xKynn/PokeCatcher#4]
Logged in.
---PokecordCatcher----
Priority: 
Catch Rate: 100%
Catch Delay: 1 seconds
Delay On Priority: On
Unregistered userID
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\websockets\protocol.py", line 528, in transfer_data
    msg = yield from self.read_message()
  File "C:\Python36\lib\site-packages\websockets\protocol.py", line 580, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "C:\Python36\lib\site-packages\websockets\protocol.py", line 645, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "C:\Python36\lib\site-packages\websockets\protocol.py", line 710, in read_frame
    extensions=self.extensions,
  File "C:\Python36\lib\site-packages\websockets\framing.py", line 128, in read
    data = yield from reader(length)
  File "C:\Python36\lib\asyncio\streams.py", line 668, in readexactly
    yield from self._wait_for_data('readexactly')
  File "C:\Python36\lib\asyncio\streams.py", line 458, in _wait_for_data
    yield from self._waiter
concurrent.futures._base.CancelledError

**Comment by madiajijah11** [comment]
Fixed, get fresh token in browser.
